name: lint

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: cargo fmt !! :3
        run: cargo fmt --check

      - name: ensure clippy is happy :D
        run: cargo clippy --all-targets --all-features -- -D warnings
